name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Publish Build Artifacts  
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: dist/

      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v2

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y k6

      - name: Run k6 Load Test
        run: |
          k6 run ./tests/performance-test.js
